[package]
name = "hanzi"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Gerd Reiss <gerd@reiss.pro>"]

[dependencies]
diesel = { version = "2.2.8", default-features = false, features = ["sqlite"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
eframe = "0.31.1"
egui = "0.31.1"
egui-modal-spinner = "0.3.0"
egui-notify = "0.19.0"
log = "0.4.26"
ollama-rs = "0.2.6"
poll-promise = { version = "0.3.0", features = ["tokio"] }
pretty_env_logger = "0.5.0"
serde = { version = "1.0.219", features = ["std", "derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
